CREATE TABLE IF NOT EXISTS users (
  id BLOB PRIMARY KEY NOT NULL,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  email_verified BOOLEAN NOT NULL DEFAULT 0,
  password_hash TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY NOT NULL,
  user_id BLOB REFERENCES users(id),
  data JSON,
  expiry_date DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS email_verification_token (
  id TEXT PRIMARY KEY NOT NULL,
  active_expires DATETIME NOT NULL,
  user_id BLOB NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS password_reset_token (
  id TEXT PRIMARY KEY NOT NULL,
  active_expires DATETIME NOT NULL,
  user_id BLOB NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
